FROM mcr.microsoft.com/devcontainers/base:trixie
#FROM debian:triexie

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

# Create a regular user for interactive use.
RUN mkdir -p /home/${USERNAME}/ \
    && chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/
#RUN mkdir -p /home/${USERNAME}/.vscode-server/data/User \
#    && chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.vscode-server/
#RUN mkdir -p /home/${USERNAME}/.local \
#    && chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.local/
#RUN mkdir -p /home/${USERNAME}/.cache \
#    && chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.cache/

USER ${USERNAME}
# WORKDIR /home/${USERNAME}
